language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - git submodule update --init --recursive
  - git submodule update --recursive

install: 
  - sudo make install

script: 
  - cd test
  - curl https://github.com/bluebird75/luaunit/blob/master/luaunit.lua > luaunit.lua
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
